name: greeter
description: Lightweight Dart package offering a Greeter utility to create friendly, customizable greetings in apps, tests, and demos.
version: 1.0.5
publish_to: https://pub.dev/packages/greeter
homepage: https://github.com/akhil-capitaire/greeter
repository: https://github.com/akhil-capitaire/greeter.git
issue_tracker: https://github.com/akhil-capitaire/greeter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
# Add regular dependencies here if needed

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
